= User Guide

== Commons Core

=== Predicates on Booleans

=== Predicates on Objects

=== Predicates on Strings

=== Predicates on Collections

=== Predicates on Integers (int and long)




=== Guards and Preconditions

precondition()
Precondition allows us to check a condition before proceeding with code. That is, if a Condition stated evaluates to false the program execution stops.
The one big condition in Precondition (LOLOLOL) is that it works in production code as well as development code. If the chosen Condition stated evaluates to false precondition will stop the executing code, and log a chosen message

Guards works slightly differently. It defines different paths through the code depending on whether the expression resolves to true or false. Because we are dealing with code paths here,


.Guards
[source,java]
----
class MyList {
    public void add(Object elm) {
        Guuards.checkNotNull(elm);
        // (...)
    }
}
----

.Preconditions
[source,java]
----
class MyList {
  private void doAdd(Object elm) {
    Preconditions.requireThat(elm).isNotNull();
    // (...)
  }
}
----

== Commons Testing

The artifact *Commons Testing** provides several utility classes for helping Java developers to write unit and integration tests.

=== Assertions

====  Number Assertions
[source,java]
----
Assertions.assertThat(value).is(11));
----

==== Object Assertions

[source,java]
----
assertThat(obj).isNull();
assertThat(obj).notNull();
----

=== Verifiers

[source,java]
----
        Verifier.verifyEqualsOf(Person.class)
                .withArguments("Anna", 33)
                .andVariants("Carol", 44)
                .check();
----
